name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  lint_compile_bump_version_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install

      - name: Compile TypeScript
        run: |
          npx tsc -p ./

      - name: Read Current Version
        id: read_version
        run: |
          if [ -f VERSION ]; then
            current_version=$(cat VERSION)
          else
            echo "0.0.0" > VERSION
            current_version="0.0.0"
          fi
          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git tag "v${{ env.new_version }}"
          git push origin "v${{ env.new_version }}"

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.new_version }}"
          release_name: "Release v${{ env.new_version }}"
          draft: false
          prerelease: false

      - name: Package and Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npx vsce package
          npx vsce publish
